/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as TrainExerciseRouteImport } from './routes/train.$exercise'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainExerciseRoute = TrainExerciseRouteImport.update({
  id: '/train/$exercise',
  path: '/train/$exercise',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/progress': typeof ProgressRoute
  '/summary': typeof SummaryRoute
  '/train/$exercise': typeof TrainExerciseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/progress': typeof ProgressRoute
  '/summary': typeof SummaryRoute
  '/train/$exercise': typeof TrainExerciseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/progress': typeof ProgressRoute
  '/summary': typeof SummaryRoute
  '/train/$exercise': typeof TrainExerciseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/dashboard'
    | '/exercises'
    | '/progress'
    | '/summary'
    | '/train/$exercise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/dashboard'
    | '/exercises'
    | '/progress'
    | '/summary'
    | '/train/$exercise'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/dashboard'
    | '/exercises'
    | '/progress'
    | '/summary'
    | '/train/$exercise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  ExercisesRoute: typeof ExercisesRoute
  ProgressRoute: typeof ProgressRoute
  SummaryRoute: typeof SummaryRoute
  TrainExerciseRoute: typeof TrainExerciseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$exercise': {
      id: '/train/$exercise'
      path: '/train/$exercise'
      fullPath: '/train/$exercise'
      preLoaderRoute: typeof TrainExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  ExercisesRoute: ExercisesRoute,
  ProgressRoute: ProgressRoute,
  SummaryRoute: SummaryRoute,
  TrainExerciseRoute: TrainExerciseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
